"""initial_schema

Revision ID: 69b72f52ca20
Revises: 
Create Date: 2025-12-18 07:39:45.131595+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69b72f52ca20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_sync_schedule',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sync_window_start', sa.Time(), server_default='19:00:00', nullable=False),
    sa.Column('sync_window_end', sa.Time(), server_default='07:00:00', nullable=False),
    sa.Column('days_to_complete', sa.Integer(), server_default='7', nullable=False),
    sa.Column('rows_per_day', sa.Integer(), nullable=True),
    sa.Column('total_rows_estimate', sa.Integer(), nullable=True),
    sa.Column('current_offset', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('next_run_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('entity_name'),
    schema='dev_schema'
    )
    op.create_table('entity_config',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('connector_api_slug', sa.String(length=100), nullable=False),
    sa.Column('business_key_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sync_schedule', sa.String(length=100), nullable=True),
    sa.Column('parent_refs_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('entity_name'),
    schema='dev_schema'
    )
    op.create_index('ix_entity_config_name', 'entity_config', ['entity_name'], unique=False, schema='dev_schema')
    op.create_table('field_mappings',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('source_field', sa.String(length=200), nullable=False),
    sa.Column('target_field', sa.String(length=200), nullable=False),
    sa.Column('transformation', sa.String(length=50), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('validation_rule', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('entity_name', 'source_field', 'target_field', name='uq_field_mapping_entity_source_target'),
    schema='dev_schema'
    )
    op.create_index('ix_field_mappings_entity', 'field_mappings', ['entity_name'], unique=False, schema='dev_schema')
    op.create_table('sync_batches',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='running', nullable=False),
    sa.Column('rows_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_normalized', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_validated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_mapped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_inserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_deleted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='dev_schema'
    )
    op.create_index('ix_sync_batches_entity', 'sync_batches', ['entity_name', 'started_at'], unique=False, schema='dev_schema')
    op.create_index('ix_sync_batches_status', 'sync_batches', ['status'], unique=False, schema='dev_schema')
    op.create_table('erp_sync_state',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('last_sync_rowversion', sa.String(length=255), nullable=True),
    sa.Column('last_sync_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_batch_uid', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_batch_uid'], ['dev_schema.sync_batches.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('entity_name', 'source_system', name='uq_erp_sync_state_entity_system'),
    schema='dev_schema'
    )
    op.create_index('ix_erp_sync_state_entity', 'erp_sync_state', ['entity_name', 'source_system'], unique=False, schema='dev_schema')
    op.create_table('failed_records',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('batch_uid', sa.UUID(), nullable=True),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mapped_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stage_failed', sa.String(length=50), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False),
    sa.Column('next_retry_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_uid'], ['dev_schema.sync_batches.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='dev_schema'
    )
    op.create_index('ix_failed_records_batch', 'failed_records', ['batch_uid'], unique=False, schema='dev_schema')
    op.create_index('ix_failed_records_retry', 'failed_records', ['next_retry_at'], unique=False, schema='dev_schema', postgresql_where=sa.text('resolved_at IS NULL'))
    op.create_table('pending_children',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('batch_uid', sa.UUID(), nullable=True),
    sa.Column('child_entity', sa.String(length=100), nullable=False),
    sa.Column('parent_entity', sa.String(length=100), nullable=False),
    sa.Column('parent_bk_hash', sa.String(length=128), nullable=False),
    sa.Column('child_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='5', nullable=False),
    sa.Column('next_retry_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_uid'], ['dev_schema.sync_batches.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='dev_schema'
    )
    op.create_index('ix_pending_children_parent', 'pending_children', ['parent_entity', 'parent_bk_hash'], unique=False, schema='dev_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pending_children_parent', table_name='pending_children', schema='dev_schema')
    op.drop_table('pending_children', schema='dev_schema')
    op.drop_index('ix_failed_records_retry', table_name='failed_records', schema='dev_schema', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_index('ix_failed_records_batch', table_name='failed_records', schema='dev_schema')
    op.drop_table('failed_records', schema='dev_schema')
    op.drop_index('ix_erp_sync_state_entity', table_name='erp_sync_state', schema='dev_schema')
    op.drop_table('erp_sync_state', schema='dev_schema')
    op.drop_index('ix_sync_batches_status', table_name='sync_batches', schema='dev_schema')
    op.drop_index('ix_sync_batches_entity', table_name='sync_batches', schema='dev_schema')
    op.drop_table('sync_batches', schema='dev_schema')
    op.drop_index('ix_field_mappings_entity', table_name='field_mappings', schema='dev_schema')
    op.drop_table('field_mappings', schema='dev_schema')
    op.drop_index('ix_entity_config_name', table_name='entity_config', schema='dev_schema')
    op.drop_table('entity_config', schema='dev_schema')
    op.drop_table('background_sync_schedule', schema='dev_schema')
    # ### end Alembic commands ###
