/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSyncRouteImport } from './routes/_app/sync'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSchedulesRouteImport } from './routes/_app/schedules'
import { Route as AppFailedRecordsRouteImport } from './routes/_app/failed-records'
import { Route as AppEntitiesRouteImport } from './routes/_app/entities'
import { Route as AppConnectorsRouteImport } from './routes/_app/connectors'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSyncRoute = AppSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulesRoute = AppSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AppRoute,
} as any)
const AppFailedRecordsRoute = AppFailedRecordsRouteImport.update({
  id: '/failed-records',
  path: '/failed-records',
  getParentRoute: () => AppRoute,
} as any)
const AppEntitiesRoute = AppEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsRoute = AppConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/connectors': typeof AppConnectorsRoute
  '/entities': typeof AppEntitiesRoute
  '/failed-records': typeof AppFailedRecordsRoute
  '/schedules': typeof AppSchedulesRoute
  '/settings': typeof AppSettingsRoute
  '/sync': typeof AppSyncRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/connectors': typeof AppConnectorsRoute
  '/entities': typeof AppEntitiesRoute
  '/failed-records': typeof AppFailedRecordsRoute
  '/schedules': typeof AppSchedulesRoute
  '/settings': typeof AppSettingsRoute
  '/sync': typeof AppSyncRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/connectors': typeof AppConnectorsRoute
  '/_app/entities': typeof AppEntitiesRoute
  '/_app/failed-records': typeof AppFailedRecordsRoute
  '/_app/schedules': typeof AppSchedulesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sync': typeof AppSyncRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/connectors'
    | '/entities'
    | '/failed-records'
    | '/schedules'
    | '/settings'
    | '/sync'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connectors'
    | '/entities'
    | '/failed-records'
    | '/schedules'
    | '/settings'
    | '/sync'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/connectors'
    | '/_app/entities'
    | '/_app/failed-records'
    | '/_app/schedules'
    | '/_app/settings'
    | '/_app/sync'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sync': {
      id: '/_app/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AppSyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedules': {
      id: '/_app/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AppSchedulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/failed-records': {
      id: '/_app/failed-records'
      path: '/failed-records'
      fullPath: '/failed-records'
      preLoaderRoute: typeof AppFailedRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entities': {
      id: '/_app/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof AppEntitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors': {
      id: '/_app/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AppConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConnectorsRoute: typeof AppConnectorsRoute
  AppEntitiesRoute: typeof AppEntitiesRoute
  AppFailedRecordsRoute: typeof AppFailedRecordsRoute
  AppSchedulesRoute: typeof AppSchedulesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSyncRoute: typeof AppSyncRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectorsRoute: AppConnectorsRoute,
  AppEntitiesRoute: AppEntitiesRoute,
  AppFailedRecordsRoute: AppFailedRecordsRoute,
  AppSchedulesRoute: AppSchedulesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSyncRoute: AppSyncRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
